SET ANSI_PADDING ON GO
CREATE NONCLUSTERED INDEX [IX_Recherche_COLONNE] ON [dbo].[TABLE](
	[COLONNE] ASC)
WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY] GO